### ISSUE TITLE
[Feature Request] Scratchpad for programs with splash screens

### ISSUE THREAD

**Issue by Dale-Muccignat** [infokiller/i3-scratchpad#8]
Hi,

I love this program and use if for almost everything that's not my immediate work.

When assigning programs with splash screens like discord it runs into an issue because it effectively needs to capture the second window that appears.

Would it be feasible to have an option line "--splash" which would wait until the second window appears before sending that window to the scratchpad?

**Comment by infokiller** [comment]
Hi,
Thanks for the kind words, I didn't know anyone else was actually using it, maybe now I'll bother to actually document it a bit...

I'll try to reproduce the issue and let you know what I think can be done, but it may take some time

**Comment by Dale-Muccignat** [comment]
Honestly it's so useful everyone should be using it. I love being able to just use a shortcut for all the apps I only need open for a little to message someone or play music. Then they're just hidden otherwise.

I'm happy to try and help discuss ideas.

So far it's either steam or discord that I've come across that has the initial "loading" window.

If you start the program first, then capture it it's fine but if the program is starting for the first time it glitches out.

**Comment by infokiller** [comment]
Hey so I took a look at this- I installed discord and opened the app and indeed I see the splash screen before the main window opens.
Just to clarify, you only need to use this feature once when you boot your machine and log in? and then it works well? this is the behavior I'm seeing when sending it to the scratchpad.

My other question is about the `--splash` idea- how would you use this exactly?
I assume you're using a keybinding to send to the scratchpad, for example `Super+s`. In this case, how would you configure i3 to use `--splash` only for steam/discord? with another shortcut?
If you want the same shortcut to work in both cases (with and without splash), you will need a more complete solution.

**Comment by Dale-Muccignat** [comment]
Correct yeah, so I use `bindsym $mod+shift+d exec "i3-scratchpad -t -d 70%x80% -m t -atc discord"` to launch discord when it has not already been opened, and it captures the splash screen into the scratchpad before the actual discord window just pops up like a normal window not in the scratchpad. Whereas if I launch discord normally first, then use the above command it captures the window fine and I can use the command like normal.

I can see what you mean about it needing to have separate commands for first launch vs normal use... that's an oversight in my initial thought. Perhaps you could make it so if --splash does not detect a second window appearing it could just capture the first.... but that sounds like it'd introduce a lot more room for error. I'm no longer sure if there is an elegant solution to be honest

**Comment by infokiller** [comment]
> so I use `bindsym $mod+shift+d exec "i3-scratchpad -t -d 70%x80% -m t -atc discord"`

Where is `i3-scratchpad` coming from here? Do you have a wrapper script? it uses args that are not supported by the script in this repo
> 
> I can see what you mean about it needing to have separate commands for first launch vs normal use... that's an oversight in my initial thought. Perhaps you could make it so if --splash does not detect a second window appearing it could just capture the first.... but that sounds like it'd introduce a lot more room for error. I'm no longer sure if there is an elegant solution to be honest

One way could be to have the splash argument get a class/instance/title, for example you may do `--scratch discord` and only if the window matches discord it will wait for the splash window.
But honestly if it only happens after a reboot, it seems like low priority to me, though I welcome PRs of course.

**Comment by Dale-Muccignat** [comment]
oh no... have I messed up completely. I got i3-scratchpad-git from the AUR and just be googling went here. Sorry I think it must be a slightly different script.....
